language: php

php:
  - 7

env:
  - TYPO3_VERSION="dev-master"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - if [ $TYPO3_VERSION == dev-master ]; then cd .Build/vendor/typo3/cms && git fetch https://review.typo3.org/Packages/TYPO3.CMS refs/changes/23/51023/4 && git checkout FETCH_HEAD && cd -; fi
  - ls -al .Build/vendor/typo3/cms/components/testing_framework
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/components/testing_framework/core/Build/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/components/testing_framework/core/Build/FunctionalTests.xml {}'
